apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: enose
  name: enose
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: enose
    spec:
      containers:
      - image: enose
        name: vguit.enose
        ports:
        - containerPort: 7070
        resources: {}
        volumeMounts:
        - mountPath: /app/config.json
          name: enose-claim0
      restartPolicy: Always
      volumes:
      - name: enose-claim0
        persistentVolumeClaim:
          claimName: enose-claim0
status: {}
