apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: node
    spec:
      containers:
      - args:
        - npm
        - start
        env:
        - name: NODE_ENV
          value: production
        image: node:8-alpine
        name: node
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /home/node/app
          name: node-claim0
        - mountPath: /home/node/models
          name: node-claim1
        workingDir: /home/node/app
      restartPolicy: Always
      volumes:
      - name: node-claim0
        persistentVolumeClaim:
          claimName: node-claim0
      - name: node-claim1
        persistentVolumeClaim:
          claimName: node-claim1
status: {}
