apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ts-server
  name: ts-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ts-server
    spec:
      containers:
      - args:
        - --model_config_file=/models/models.config
        image: tensorflow/serving:latest
        name: vguit.enose.ts.serving
        ports:
        - containerPort: 8500
        - containerPort: 8501
        resources: {}
        volumeMounts:
        - mountPath: /models
          name: ts-server-claim0
      restartPolicy: Always
      volumes:
      - name: ts-server-claim0
        persistentVolumeClaim:
          claimName: ts-server-claim0
status: {}
